### ISSUE TITLE
bumblebee not working (failed to start compiling) in fedora 22

### ISSUE THREAD

**Issue by rudrab** [Bumblebee-Project/Bumblebee#647]
Hi,
I am a regular bumblebee user.
In fedora 22 (alpha) I am having problem:
# systemctl status bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/usr/lib/systemd/system/bumblebeed.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2015-04-03 11:16:32 BST; 49s ago
  Process: 6242 ExecStart=/usr/sbin/bumblebeed (code=exited, status=1/FAILURE)
 Main PID: 6242 (code=exited, status=1/FAILURE)

Apr 03 11:16:32 roddur systemd[1]: Unit bumblebeed.service entered failed state.
Apr 03 11:16:32 roddur systemd[1]: bumblebeed.service failed.
# systemctl status bumblebee-nvidia.service 
● bumblebee-nvidia.service - Compiling NVidia Driver
   Loaded: loaded (/etc/systemd/system/bumblebee-nvidia.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2015-04-03 11:08:50 BST; 5min ago
  Process: 652 ExecStart=/usr/sbin/bumblebee-nvidia (code=exited, status=1/FAILURE)
 Main PID: 652 (code=exited, status=1/FAILURE)

Apr 03 11:08:22 roddur systemd[1]: Starting Compiling NVidia Driver...
Apr 03 11:08:24 roddur bumblebee-nvidia[652]: --force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Apr 03 11:08:26 roddur bumblebee-nvidia[652]: Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-346.47
Apr 03 11:08:27 roddur bumblebee-nvidia[652]: Verifying archive integrity... OK
Apr 03 11:08:35 roddur bumblebee-nvidia[652]: Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 346.47................................
Apr 03 11:08:50 roddur bumblebee-nvidia[652]: [FAILED]
Apr 03 11:08:50 roddur systemd[1]: bumblebee-nvidia.service: main process exited, code=exited, status=1/FAILURE
Apr 03 11:08:50 roddur systemd[1]: Failed to start Compiling NVidia Driver.
Apr 03 11:08:50 roddur systemd[1]: Unit bumblebee-nvidia.service entered failed state.
Apr 03 11:08:50 roddur systemd[1]: bumblebee-nvidia.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

I am using 
# rpm -qa bumblebee*
bumblebee-release-1.2-1.noarch
bumblebee-nonfree-release-1.2-1.noarch
bumblebee-3.2.1-7.fc22.x86_64
bumblebee-nvidia-346.47-1.fc22.x86_64

# uname -r
4.0.0-0.rc5.git4.1.fc22.x86_64

Kindly help

**Comment by gsgatlin** [comment]
Hello,

Since this is closed source software there is little I can do. I'm sorry. I did verify it is not working and have opened a topic on the "Developer Zone" here:

https://devtalk.nvidia.com/default/topic/823073/linux/346-47-on-fedora-22-kernel-4-0-0-0-rc5-git4-1-fc22-x86_64/

So you may want to keep checking on that. Maybe when a new kernel comes out for fedora 22 it will be fixed.

**Comment by rudrab** [comment]
hi gsgatlin,
Thanks for your prompt support.
Are you considering implement the patch they provided?

**Comment by gsgatlin** [comment]
Ok, I got it to work finally on a test machine but there were some SELinux changes in fedora 22. So its working for me in enforcing mode but hopefully they will not change it too much more before release date. Tested with both primus and virtualgl.  I am using fedora 21 right now but will upgrade to fedora 22 after final release date.

Selinux module:
http://fpaste.org/207078/09624214/

So I'm just going to update this for f22 since f21 is working fine. But the rpm itself has logic which will only add the patch for fedora 22. (and newer)

@ArchangeGabriel fedora 22 alpha is using xorg-x11-server-Xorg-1.17.1-7.fc22.x86_64 but this is with nvidia. I have not had a chance yet to test it with nouveau. I still have xorg-x11-server-Xorg-1.16.3-2.fc21.x86_64 on my laptop here which I use with nvidia. I will test it next week on fedora 22 alpha with nouveau.


@rudrab so what you need to do is this.

You may need to clean your dnf cache first.

dnf update bumblebee-nvidia

Then reboot/recompile

fix in bumblebee-nvidia-346.47-2.fc22. Let me know if it fixes it.

Thanks.

**Comment by rudrab** [comment]
Thanks, 
Its working perfectly. 
Just to inform, it got stuck at compilation after the boot,  but I think that is more to fedora than bumblebee. 
You are also right in we need to setenforce 0.
But, its working nonetheless. 
On Fri, Apr 03, 2015 at 10:48 pm, gsgatlin <notifications@github.com> wrote:Ok, I got it to work finally on a test machine but there were some SELinux changes in fedora 22. So its working for me in enforcing mode but hopefully they will not change it too much more before release date. Tested with both primus and virtualgl.  I am using fedora 21 right now but will upgrade to fedora 22 after final release date.

Selinux module:
http://fpaste.org/207078/09624214/

So I'm just going to update this for f22 since f21 is working fine. But the rpm itself has logic which will only add the patch for fedora 22. (and newer)

@ArchangeGabriel fedora 22 alpha is using xorg-x11-server-Xorg-1.17.1-7.fc22.x86_64 but this is with nvidia. I have not had a chance yet to test it with nouveau. I still have xorg-x11-server-Xorg-1.16.3-2.fc21.x86_64 on my laptop here which I use with nvidia. I will test it next week on fedora 22 alpha with nouveau.

@rudrab so what you need to do is this.

You may need to clean your dnf cache first.

dnf update bumblebee-nvidia

Then reboot/recompile

fix in bumblebee-nvidia-346.47-2.fc22. Let me know if it fixes it.

Thanks.

**Comment by rudrab** [comment]
Hi,
This same issue has returned with f22 beta.

**Comment by gsgatlin** [comment]
Hello.

I believe this has been fixed with kernel 4.0.1-300.fc22. Try updating and see if its working for you now.

Cheers.

**Comment by Gordin** [comment]
This bug still (or again) exists in fedora 22. Kernel version is now 4.1.10-200.fc22.x86_64
